export enum Allergen
{
    None ="None",
    Wheat ="Wheat",
    Barley ="Barley",
    Rye ="Rye",
    Oats ="Oats",
    Almonds ="Almonds",
    Hazelnuts ="Hazelnuts",
    Walnuts ="Walnuts",
    Pecans ="Pecans",
    BrazilNuts ="BrazilNuts",
    Pistachio ="Pistachio",
    Cashew ="Cashew",
    Macadamia ="Macadamia",
    QueenslandNut ="QueenslandNut",
    Milk ="Milk",
    Eggs ="Eggs",
    Soya ="Soya",
    Crustaceans ="Crustaceans",
    Fish ="Fish",
    Celery ="Celery",
    Mustard ="Mustard",
    Sesame ="Sesame",
    SulphurDioxide ="SulphurDioxide",
    Lupin ="Lupin",
    Legumes ="Legumes",
    Molluscs ="Molluscs",
}