# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - MarryMonio

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VITE_API_URL: ${{vars.VITE_APP_API_URL}}
  VITE_APP_API_URL: ${{vars.VITE_APP_API_URL}}
  VITE_APP_API_SERVER_URL: ${{vars.VITE_APP_API_SERVER_URL}}
  VITE_APP_AUTH0_DOMAIN: ${{vars.VITE_APP_AUTH0_DOMAIN}}
  VITE_APP_AUTH0_CLIENT_ID: ${{vars.VITE_APP_AUTH0_CLIENT_ID}}
  VITE_APP_AUTH0_CALLBACK_URL: ${{vars.VITE_APP_AUTH0_CALLBACK_URL}}
  VITE_APP_AUTH0_AUDIENCE: ${{vars.VITE_APP_AUTH0_AUDIENCE}}
  VITE_APP_AUTH0_MANAGEMENT_API_TOKEN=: ${{vars.VITE_APP_AUTH0_MANAGEMENT_API_TOKEN}}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: create env file
        run: |
          touch .env
          echo VITE_APP_AUTH0_DOMAIN=${{ vars.VITE_APP_AUTH0_DOMAIN }} >> .env
          echo VITE_APP_API_URL=${{ vars.VITE_APP_API_URL }} >> .env
          echo VITE_APP_API_SERVER_URL=${{ vars.VITE_APP_API_SERVER_URL }} >> .env
          echo VITE_APP_AUTH0_CLIENT_ID=${{ vars.VITE_APP_AUTH0_CLIENT_ID }} >> .env
          echo VITE_APP_AUTH0_CALLBACK_URL=${{ vars.VITE_APP_AUTH0_CALLBACK_URL }} >> .env
          echo VITE_APP_AUTH0_AUDIENCE=${{ vars.VITE_APP_AUTH0_AUDIENCE }} >> .env
          echo VITE_APP_AUTH0_MANAGEMENT_API_TOKEN=${{ secrets.VITE_APP_AUTH0_MANAGEMENT_API_TOKEN }} >> .env
    
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_49C443465AE7412FAD43D7D2345DE98D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FB799C41A52947A5B4DE31FF792FED3B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_73737847086B4F65BBD90915AAB59972 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MarryMonio'
          slot-name: 'Production'
          package: .
          
